import { makeStyles } from '@mui/styles';

export default makeStyles((theme) => ({
  media: {
    height: 0,
    paddingTop: '56.25%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    backgroundBlendMode: 'darken',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    objectFit: 'cover',
  },
  border: {
    border: 'solid',
  },
  fullHeightCard: {
    height: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderRadius: '15px !important',
    height: '100%',
    position: 'relative',
    width: '100%',
    maxWidth: '100%',
    overflow: 'hidden',
    minHeight: '450px',
    '&:hover': {
      transform: 'scale(1.02)',
      transition: 'transform 0.3s ease-in-out',
    },
  },
  overlay: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    color: 'white',
    zIndex: 1,
  },
  overlay2: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    color: 'white',
    zIndex: 1,
  },
  grid: {
    display: 'flex',
  },
  details: {
    display: 'flex',
    justifyContent: 'space-between',
    margin: '20px',
    flexWrap: 'wrap',
    gap: '8px',
  },
  title: {
    padding: '0 16px',
    marginTop: '8px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  cardContent: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '16px',
    overflow: 'hidden',
  },
  message: {
    flexGrow: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    marginBottom: '8px',
  },
  cardActions: {
    padding: '0 16px 8px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    borderTop: '1px solid rgba(0, 0, 0, 0.1)',
    marginTop: 'auto',
  },
  clickableArea: {
    cursor: "pointer",
    transition: "background-color 0.2s ease-in-out",
    "&:hover": {
        backgroundColor: "rgba(107, 107, 107, 0.1)",
    },
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
}));